// Conteúdo do site.
window.MM_DATA = {
  artist: {
    name: "Fios de Aracne",
    signature: "feito com amor",
    maker: "Raven",
    handle: "@r4ven.vmp",
    igUrl: "https://www.instagram.com/r4ven.vmp/",
    waUrl: "https://wa.me/556293736614",
    tagline: "amigurumis & crochê com alma",
    sub: "feito à mão por uma estudante de arte do IFG — cada peça carrega um pedacinho de mim.",
  },
  stats: [
    { value: "+240", label: "bichinhos adotados" },
    { value: "3–9", label: "dias por peça" },
    { value: "100%", label: "fio premium" },
  ],
  obsessions: [
    "filmes de terror & goticismo",
    "crochê, arte e coisas feitas à mão",
    "playlists dramáticas pra criar",
    "energético geladinho na madrugada",
  ],
  pricing: {
    headline: "preço justo, feito a mão",
    formula: "R$15 por hora de trabalho + custo da linha",
    note: "cada peça leva de 3 a 15 horas — o valor varia por tamanho, complexidade e cores.",
  },
  pieces: [
    {
      id: "salem",
      name: "Salem",
      kind: "gatinho de gola",
      priceFrom: 140,
      hours: "aprox. 9h",
      photo: "assets/produto-gato.jpg",
      note: "olhos enormes, alma de bruxo",
      desc: "amigurumi de gato preto em fio chenille (felpudinho), olhos bordados em amarelo, golinha branca. tem braços e pernas articulados que abraçam.",
      size: "aprox. 28cm",
      yarn: "fio chenille premium",
    },
    {
      id: "medusa",
      name: "Medusa",
      kind: "água-viva flutuante",
      priceFrom: 95,
      hours: "aprox. 5h",
      photo: "assets/produto-aguaviva.jpg",
      note: "feita pra pendurar e balançar",
      desc: "água-viva de crochê com tentáculos longos em fio cru e lilás. linda pendurada no teto do quarto ou na janela.",
      size: "aprox. 35cm com tentáculos",
      yarn: "fio cisne 100% algodão",
    },
    {
      id: "yuki",
      name: "Touca Yuki",
      kind: "touca de orelhinha + laço",
      priceFrom: 75,
      hours: "aprox. 4h",
      photo: "assets/produto-toucagato.jpg",
      note: "kawaii até no inverno",
      desc: "touca em ponto baixo com orelhinhas de gatinho e laço aplicado. branca com laço vermelho — escolha sua combinação.",
      size: "tamanhos P/M/G",
      yarn: "fio cisne 100% algodão",
    },
    {
      id: "moranguinho",
      name: "Top Moranguinho",
      kind: "top frutinha",
      priceFrom: 110,
      hours: "aprox. 7h",
      photo: "assets/produto-top-morango.jpg",
      note: "verão eterno",
      desc: "top de crochê vermelho com babado verde em formato de morango. amarração no pescoço e nas costas, tamanho sob medida.",
      size: "sob medida",
      yarn: "barbante cor sólida",
    },
    {
      id: "reggae",
      name: "Conjunto Reggae",
      kind: "biquíni + saída",
      priceFrom: 240,
      hours: "aprox. 14h",
      photo: "assets/produto-bikini-reggae.jpg",
      note: "verão & sound system",
      desc: "conjunto completo: top de biquíni com as cores rasta + saída de praia em ponto vazado preta com listras vermelho/amarelo/verde. botões funcionais.",
      size: "sob medida",
      yarn: "barbante de algodão",
    },
    {
      id: "sob-encomenda",
      name: "Sua peça",
      kind: "criação sob medida",
      priceFrom: null,
      hours: "a combinar",
      photo: null,
      note: "manda referência, eu rascunho",
      desc: "tem uma ideia na cabeça? me chama no Instagram com referências, fotos, ou só descreve a vibe. eu rascunho, a gente conversa, ajusta e construo.",
      size: "varia",
      yarn: "varia",
      isCustom: true,
    },
  ],
  process: [
    { n: "01", title: "a conversa", text: "tudo começa no direct. me conta o que quer, manda referência, descreve a vibe. eu pergunto bastante." },
    { n: "02", title: "o orçamento", text: "estimo as horas + custo da linha e te mando o valor antes de começar. tudo transparente." },
    { n: "03", title: "o feitiço", text: "ponto por ponto, em geral 3 a 15 horas de trabalho. mando foto do processo se você quiser ver crescendo." },
    { n: "04", title: "a entrega", text: "embalada em saquinho de cetim com bilhete escrito à mão. envio pra todo Brasil." },
  ],
};
